### Дана целочисленная квадратная матрица. Определить:
1. Сумму элементов в тех столбцах, которые не содержат отрицательных элементов;
2. Минимум среди сумм модулей элементов диагоналей, параллельных побочной диагонали
матрицы.

In [1]:
import numpy as np

In [2]:
n=int(input("Введите размерность матрицы: "))

Введите размерность матрицы: 4


In [10]:
a=np.random.randint(-5,30,(n,n))
print(a)

[[-5 23 26 24]
 [24 15  3 14]
 [17  1  3 27]
 [20 -5  5 22]]


#### Сумму элементов в тех столбцах, которые не содержат отрицательных элементов

In [11]:
print(a[:, a.min(axis=0) > 0])


[[26 24]
 [ 3 14]
 [ 3 27]
 [ 5 22]]


In [12]:
summ = np.sum(a[:, a.min(axis=0) > 0])
print(summ)

124


#### Минимум среди сумм модулей элементов диагоналей, параллельных побочной диагонали матрицы.

Для начала с помощью функции absolute() применяем к матрице модуль

In [17]:
b=np.absolute(a)
print(b)

[[ 5 23 26 24]
 [24 15  3 14]
 [17  1  3 27]
 [20  5  5 22]]


Фунеция trace() позволяем получить сумму по главной диагонали со смещением offset

In [24]:
print(b.trace(offset=1))
print(b.trace(offset=-1))

53
30


Чтобы получить побочную диагональ нужно будет перевернуть матрицу с помощью функциии fliplr()

In [19]:
print(np.fliplr(b))

[[24 26 23  5]
 [14  3 15 24]
 [27  3  1 17]
 [22  5  5 20]]


В списковом включении используем упомянутые выше функции 

In [25]:
minn=min([np.flip(b).trace(offset=i) for i in range(-(n-2),n-1)])
minn

22