### Дана целочисленная квадратная матрица. Определить:
1. Сумму элементов в тех столбцах, которые не содержат отрицательных элементов;
2. Минимум среди сумм модулей элементов диагоналей, параллельных побочной диагонали
матрицы.

In [1]:
import numpy as np

In [2]:
n=int(input("Введите размерность матрицы: "))

Введите размерность матрицы: 4


In [3]:
a=np.random.randint(-5,30,(n,n))
print(a)

[[-2  4  9 14]
 [11  6  9 11]
 [28 28 -4 -4]
 [ 3 27 15 16]]


#### Сумму элементов в тех столбцах, которые не содержат отрицательных элементов

In [4]:
for col in range (n):
    summ=0
    for row in range(n):
        if a[row][col]<0:
            break
        summ+=a[row][col]
    else:
        print(f"Сумма {col+1} столбца: {summ}")

Сумма 2 столбца: 65


#### Минимум среди сумм модулей элементов диагоналей, параллельных побочной диагонали матрицы.

In [9]:
a=np.absolute(a)
print(a)
print(min([a[i+1][i]+a[i][i+1] for i in range (n-1)]))

[[ 2  4  9 14]
 [11  6  9 11]
 [28 28  4  4]
 [ 3 27 15 16]]
15
